version: '2'
networks:
  default:
    external:
      name: cic

services:
  server1:
    image: ${CIC_COURSEWARE_IMAGE}:${CIC_COURSEWARE_VERSION}
    command: /sbin/init

  server2:
    image: ${CIC_COURSEWARE_IMAGE}:${CIC_COURSEWARE_VERSION}
    command: /sbin/init

  server3:
    image: ${CIC_COURSEWARE_IMAGE}:${CIC_COURSEWARE_VERSION}
    command: /sbin/init

