---
- hosts: apache
  become: sudo
  tasks:
    - name: install httpd
      apt: name=apache2 update_cache=yes state=latest
#
    - name: Start service httpd, if not running
      service:
        name: apache2
        enabled: yes
        state: started

#    - name: blah
#      shell: systemctl enable httpd.service

#  handlers:
#    - name: restart httpd
#      service: name=httpd state=restarted
